package zheng.py;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Mon Dec 10 23:50:21 EST 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1355201405858L;
    public static final String CHECKSUM = "1555a592c21c81daf4a7ab64c20082a4";
    public static final String BARRISTER_VERSION = "0.1.4";

}

