package zheng.py;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Mon Dec 10 23:50:21 EST 2012
 */

public interface Predictor {

    public Double predict(String inst_str) throws com.bitmechanic.barrister.RpcException;

}

